       //LOOPJOB  JOB (ACCT),'LOOP ENGINEERING',CLASS=A,MSGCLASS=X
       //STEP01   EXEC PGM=TRANSACTION-SUMMARY
       //INPUTDD  DD DSN=APP.TRANSACTIONS.INPUT,DISP=SHR
       //OUTPUTDD DD DSN=APP.TRANSACTIONS.SUMMARY,
       //            DISP=(NEW,CATLG,DELETE),
       //            DCB=(RECFM=FB,LRECL=80,BLKSIZE=800)
